# Load the Libraries

In [1]:
# importing libraries
import pandas as pd
import numpy as np

# Load the DataSet

In [2]:
#Read the movie Dataset
i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv('ml-100k/u.item', sep='|', names=i_cols,encoding='latin-1')

In [3]:
# Select only needed Item
movie_content=items[['movie id','movie title']]

In [4]:
movie_content

      movie id                                movie title
0            1                           Toy Story (1995)
1            2                           GoldenEye (1995)
2            3                          Four Rooms (1995)
3            4                          Get Shorty (1995)
4            5                             Copycat (1995)
...        ...                                        ...
1677      1678                          Mat' i syn (1997)
1678      1679                           B. Monkey (1998)
1679      1680                       Sliding Doors (1998)
1680      1681                        You So Crazy (1994)
1681      1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [5]:
# reading ratings file:
r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv('ml-100k/u.data', sep='\t', names=r_cols,encoding='latin-1')

In [6]:
ratings

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [7]:
n_users = ratings.user_id.unique().shape[0]
n_items = ratings.movie_id.unique().shape[0]

In [8]:
print("The number of user:",n_users)
print("The number of n_items:",n_items)

The number of user: 943
The number of n_items: 1682

In [9]:
df = pd.DataFrame(ratings)

In [10]:
df

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [11]:
df_unique = df.groupby('movie_id', as_index=False).first()

In [12]:
df_unique

      movie_id  user_id  rating  unix_timestamp
0            1      308       4       887736532
1            2        5       3       875636053
2            3      181       2       878963441
3            4       99       5       886519097
4            5      293       3       888906576
...        ...      ...     ...             ...
1677      1678      863       1       889289570
1678      1679      863       3       889289491
1679      1680      863       2       889289570
1680      1681      896       3       887160722
1681      1682      916       3       880845755

[1682 rows x 4 columns]

In [13]:
data=pd.concat([movie_content,df_unique], axis=1)

In [14]:
data

,movie id,movie title,movie_id,user_id,rating,unix_timestamp
0,1,Toy Story (1995),1,308,4,887736532
1,2,GoldenEye (1995),2,5,3,875636053
2,3,Four Rooms (1995),3,181,2,878963441
3,4,Get Shorty (1995),4,99,5,886519097
4,5,Copycat (1995),5,293,3,888906576
...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),1678,863,1,889289570
1678,1679,B. Monkey (1998),1679,863,3,889289491
1679,1680,Sliding Doors (1998),1680,863,2,889289570
1680,1681,You So Crazy (1994),1681,896,3,887160722
1681,1682,Scream of Stone (Schrei aus Stein) (1991),1682,916,3,880845755

In [18]:
high_rat=data[data['rating']>4][['movie_id','movie title','rating']]

In [19]:
high_rat

      movie_id                                        movie title  rating
3            4                                  Get Shorty (1995)       5
9           10                                 Richard III (1995)       5
10          11                               Seven (Se7en) (1995)       5
11          12                         Usual Suspects, The (1995)       5
25          26                      Brothers McMullen, The (1995)       5
...        ...                                                ...     ...
1598      1599                      Someone Else's America (1995)       5
1611      1612                            Leading Man, The (1996)       5
1616      1617                                   Hugo Pool (1997)       5
1627      1628                                    Lamerica (1994)       5
1652      1653  Entertaining Angels: The Dorothy Day Story (1996)       5

[259 rows x 3 columns]

In [20]:
high_rat.head(5)

    movie_id                    movie title  rating
3          4              Get Shorty (1995)       5
9         10             Richard III (1995)       5
10        11           Seven (Se7en) (1995)       5
11        12     Usual Suspects, The (1995)       5
25        26  Brothers McMullen, The (1995)       5

In [21]:
#Read the movie Dataset
i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv('ml-100k/u.item', sep='|', names=i_cols,encoding='latin-1')

In [22]:
# Select only needed Item
genere=items[['movie id','movie title','Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]

In [23]:
genere

,movie id,movie title,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [ ]:
#Create pivot table for user and movie basedon ratings

In [ ]:
datama=data.pivot_table(index='user_id',columns='movie_id',values='rating')

In [ ]:
#Replace with nan with 0
data_matrix=datama.replace(np.nan,0)

In [ ]:
data_matrix

# Find Cosine Similatity for user and Item

In [ ]:
from sklearn.metrics.pairwise import pairwise_distances 
user_similarity = pairwise_distances(data_matrix, metric='cosine')
item_similarity = pairwise_distances(data_matrix.T, metric='cosine')

In [ ]:
item_similarity

# Using formula for user and item we are calcuating the score value

In [ ]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1).to_numpy()
        #We use np.newaxis so that mean_user_rating has same format as ratings
        ratings_diff = (ratings - mean_user_rating[:, np.newaxis])
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [ ]:
# prediction Table
user_prediction = predict(data_matrix, user_similarity, type='user')
item_prediction = predict(data_matrix, item_similarity, type='item')

In [ ]:
user_prediction

### As per popularity based filtering ,for new users we can recom top 5 movies

In [ ]:
#1. Select input item

input_item=34

In [ ]:
#2. Convert the item_sim table into DataFrame

item_sim_table=pd.DataFrame(item_similarity)

In [ ]:
item_sim_table

In [ ]:
#3. Find similarity item for 34 using cosine table

similar_input_item= item_sim_table[input_item].sort_values(ascending=True).head(5).index

In [ ]:
similar_input_item

In [ ]:
#4.Convert in to list

similar_item_input=list(similar_input_item)

In [ ]:
#5. Using similar_item_input,can select movie id from ratings table

similar_item_userid_list=[]
for sim_item in similar_item_input:
    sim=list(ratings[ratings['movie_id']==sim_item]['user_id'])
    similar_item_userid_list.append(sim)

In [ ]:
similar_item_userid_list

In [ ]:
#6. Convert all the list as single
import itertools
similar_item_userid_single_list=list(itertools.chain.from_iterable(similar_item_userid_list))

In [ ]:
similar_item_userid_single_list

In [ ]:
#7. Unique userid from the list

Unique_userid_similar_item=set(similar_item_userid_single_list)

In [ ]:
len(Unique_userid_similar_item)

In [ ]:
#8. Input item watched by user id

input_item_watched_userid=list(ratings[ratings['movie_id']==input_item]['user_id'].values)

In [ ]:
input_item_watched_userid

In [ ]:
#9. Create a list which should have recom userid to the input item

recom=[]
for per_id in Unique_userid_similar_item:
    if(per_id in input_item_watched_userid):
        pass
    else:
        recom.append(per_id)

In [ ]:
len(recom)

In [ ]:
sorted(recom)

In [ ]:
# Cross Checking 
sorted(Unique_userid_similar_item)

In [ ]:
# Cross Checking
sorted(input_item_watched_userid)

In [ ]:
# Checking the common movie list
list(set(Unique_userid_similar_item)&set(input_item_watched_userid))

In [ ]:
item_pred=pd.DataFrame(item_prediction)

In [ ]:
item_pred

In [ ]:
#s[187].values >=0.4

In [ ]:
item_pred[input_item]

In [ ]:
# From recomd list select hightest rated userid which would selected by the item. Based on item prediction

highest_Rated=[]
input_item_pre=pd.DataFrame(item_pred[input_item])
input_item_pred=input_item_pre.T
for re in recom:
    value=input_item_pred[re].values
    if(value>=1):
        highest_Rated.append(re)

In [ ]:
len(highest_Rated)

In [ ]:
# Checking the common movie list
list(set(recom)&set(input_item_watched_userid))

In [ ]:
def itembased(input_item,item_similarity,item_predictions,similar_item_count,thres):
    #Convert the item_sim table into DataFrame
    item_sim_table=pd.DataFrame(item_similarity)
    #Find similarity item for 34 using cosine table
    similar_input_item= item_sim_table[input_item].sort_values(ascending=True).head(similar_item_count).index
    #Convert in to list
    similar_item_input=list(similar_input_item) 
    #Using similar_item_input,can select user id from ratings table
    similar_item_userid_list=[]
    for sim_item in similar_item_input:
        sim=list(ratings[ratings['movie_id']==sim_item]['user_id'])
        similar_item_userid_list.append(sim)
    #Converting as a whole list
    import itertools
    similar_item_userid_single_list=list(itertools.chain.from_iterable(similar_item_userid_list))
    #Unique userid from the list
    Unique_userid_similar_item=set(similar_item_userid_single_list)
    #Input item watched by userid
    input_item_watched_userid=list(ratings[ratings['movie_id']==input_item]['user_id'].values)
    #Create a list which should have recom userid to the input item
    recom=[]
    for per_id in Unique_userid_similar_item:
        if(per_id in input_item_watched_userid):
            pass
        else:
            recom.append(per_id)
    #From recommendation list selecting only hightest rated(predicted) value
    highest_Rated=[]
    user_pred=pd.DataFrame(item_prediction)
    input_item_pre=pd.DataFrame(user_pred[input_item])
    input_item_pred=input_item_pre.T
    for re in recom:
        value=input_item_pred[re].values
        if(value>=thres):
            highest_Rated.append(re)
    highest_Rated
    return highest_Rated

In [ ]:
#def itembased(input_user,user_similarity,user_predictions,similar_user_count,similar_user_movieid_count,thres):
Recommended_user=itembased(5,item_similarity,item_pred,5,0.8)

In [ ]:
len(Recommended_user)

In [ ]:
Recommended_user