In [1]:
# Load the Libraries

In [2]:
# importing libraries
import pandas as pd
import numpy as np

In [3]:
# Load the DataSet

In [4]:
#Read the movie Dataset
i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv('ml-100k/u.item', sep='|', names=i_cols,encoding='latin-1')

In [5]:
# Select only needed Item
movie_content=items[['movie id','movie title']]

In [6]:
movie_content

      movie id                                movie title
0            1                           Toy Story (1995)
1            2                           GoldenEye (1995)
2            3                          Four Rooms (1995)
3            4                          Get Shorty (1995)
4            5                             Copycat (1995)
...        ...                                        ...
1677      1678                          Mat' i syn (1997)
1678      1679                           B. Monkey (1998)
1679      1680                       Sliding Doors (1998)
1680      1681                        You So Crazy (1994)
1681      1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [7]:
# reading ratings file:
r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv('ml-100k/u.data', sep='\t', names=r_cols,encoding='latin-1')

In [8]:
ratings

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [9]:
n_users = ratings.user_id.unique().shape[0]
n_items = ratings.movie_id.unique().shape[0]

In [10]:
print("The number of user:",n_users)
print("The number of n_items:",n_items)

The number of user: 943
The number of n_items: 1682

In [11]:
df = pd.DataFrame(ratings)

In [12]:
df

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [13]:
df_unique = df.groupby('movie_id', as_index=False).first()

In [14]:
df_unique

      movie_id  user_id  rating  unix_timestamp
0            1      308       4       887736532
1            2        5       3       875636053
2            3      181       2       878963441
3            4       99       5       886519097
4            5      293       3       888906576
...        ...      ...     ...             ...
1677      1678      863       1       889289570
1678      1679      863       3       889289491
1679      1680      863       2       889289570
1680      1681      896       3       887160722
1681      1682      916       3       880845755

[1682 rows x 4 columns]

In [15]:
data=pd.concat([movie_content,df_unique], axis=1)

In [16]:
data

,movie id,movie title,movie_id,user_id,rating,unix_timestamp
0,1,Toy Story (1995),1,308,4,887736532
1,2,GoldenEye (1995),2,5,3,875636053
2,3,Four Rooms (1995),3,181,2,878963441
3,4,Get Shorty (1995),4,99,5,886519097
4,5,Copycat (1995),5,293,3,888906576
...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),1678,863,1,889289570
1678,1679,B. Monkey (1998),1679,863,3,889289491
1679,1680,Sliding Doors (1998),1680,863,2,889289570
1680,1681,You So Crazy (1994),1681,896,3,887160722
1681,1682,Scream of Stone (Schrei aus Stein) (1991),1682,916,3,880845755

In [17]:
high_rat=data[data['rating']>4][['movie_id','movie title','rating']]

In [18]:
high_rat

      movie_id                                        movie title  rating
3            4                                  Get Shorty (1995)       5
9           10                                 Richard III (1995)       5
10          11                               Seven (Se7en) (1995)       5
11          12                         Usual Suspects, The (1995)       5
25          26                      Brothers McMullen, The (1995)       5
...        ...                                                ...     ...
1598      1599                      Someone Else's America (1995)       5
1611      1612                            Leading Man, The (1996)       5
1616      1617                                   Hugo Pool (1997)       5
1627      1628                                    Lamerica (1994)       5
1652      1653  Entertaining Angels: The Dorothy Day Story (1996)       5

[259 rows x 3 columns]

In [19]:
high_rat.head(5)

    movie_id                    movie title  rating
3          4              Get Shorty (1995)       5
9         10             Richard III (1995)       5
10        11           Seven (Se7en) (1995)       5
11        12     Usual Suspects, The (1995)       5
25        26  Brothers McMullen, The (1995)       5